### ISSUE TITLE
计划第一版是什么时候出来。

### ISSUE THREAD

**Issue by windli93** [disoul/electron-cloud-music#1]
是和官方人员一起开发还是个人的爱好呢。

**Comment by disoul** [comment]
个人爱好，计划第一版在5月底出来，因为6月要考试了

**Comment by windli93** [comment]
挺不错啊，看好你。

**Comment by windli93** [comment]
debian8.4 64位无法安装依赖模块，你能打成一个deb包吗？

**Comment by disoul** [comment]
现在这个版本不需要依赖啊，直接从release上下载解压运行可执行文件就行了啊，如果有问题麻烦贴出来报错

**Comment by windli93** [comment]
运行了你tar包，进来的时候页面太大了，能不能改小点。

**Comment by windli93** [comment]
![2016-05-10 13-50-43](https://cloud.githubusercontent.com/assets/16792321/15136806/401a7570-16b7-11e6-8eea-6cc721b7e620.png)

![2016-05-10 13-52-02](https://cloud.githubusercontent.com/assets/16792321/15136829/83dd5840-16b7-11e6-80ba-361e2dbfc231.png)
真心太大了。

**Comment by windli93** [comment]
对了，求推荐node.js书籍和electron的资料，我打算开发一款Feedly阅读器的桌面应用。

**Comment by disoul** [comment]
唔页面大因为自己开发的时候显示器比较大吧。。。得改成rem布局
nodejs和electron推荐看官方文档吧，个人没有看书的习惯。。。

**Comment by windli93** [comment]
你也是牛逼.......
