### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by imzf** [disoul/electron-cloud-music#3]
提示 Error:{"code":502}
我反复确认了好几次，密码和用户名都没打错

**Comment by disoul** [comment]
502这个错是由于邮箱登陆密码错误
邮箱只支持网易邮箱也就是163.com结尾的
如果不行的话可以在命令行下运行CloudMusic然后麻烦把log贴上来(log里密码哈希过了不用担心

**Comment by imzf** [comment]
哦，我是用谷歌邮箱注册的账户
