### ISSUE TITLE
一只跑不起来，这个错误我怎么干掉它呢

### ISSUE THREAD

**Issue by lebornjose** [disoul/electron-cloud-music#5]
<img width="1022" alt="qq20160908-0 2x" src="https://cloud.githubusercontent.com/assets/5765408/18338908/ba779ab6-75ce-11e6-8f6b-00006ce70013.png">

**Comment by disoul** [comment]
你的webpack版本是2.1.0-beta5么

**Comment by lebornjose** [comment]
不是的，通过 npm install webpack@2.1.0-beta.5 -g  来安装，哪次都出现，
![33](https://cloud.githubusercontent.com/assets/5765408/18340314/d27aa4b6-75d6-11e6-8720-5017f1bb51b8.png)

**Comment by disoul** [comment]
这之后直接`webpack-dev-server --inline --compress --content-base=./`试试

**Comment by lebornjose** [comment]
就是运行这段代码后,才出现了之前的第一个错误，然后我更改了 .babelrc 文件 改成

{ "presets": [ [ "es2015", { "modules": false } ] ] }  ，就会出现jsx 语法编辑不通过

**Comment by disoul** [comment]
webpack2之后对babel的支持变了，你可以改用webpack1来build把config改一下

**Comment by lebornjose** [comment]
好的,thanks
