### ISSUE TITLE
问几个问题，我想学习一下。

### ISSUE THREAD

**Issue by magic-akari** [disoul/electron-cloud-music#6]
我有几个疑问想请教一下。

1. 为什么需要 express 框架来转发请求？直接食用云音乐的 API 有哪些缺点？
2. 为什么需要 babel 转码？electron 里带的 Node/Chromium 对 JS5 语法支持还不行吗？或者使用更前卫的语法？

ReactJS 等框架我是刚刚初学，疑惑的地方太多。

**Comment by disoul** [comment]
1. 直接在浏览器端构造请求无法伪造refer头，网易后端会检测refer
2. babel转jsx啊，babel等配置是从我以前的配置直接拉过来的就没怎么改了。目前来看前端代码babel转码还是有必要的，后端上node7+harmony的话倒是可以摆脱babel了

**Comment by disoul** [comment]
还有，写这个项目的时候我也是react初学，很多地方现在来看有些不规范，比如组件化还有redux的使用等等，希望不要误导到你XD

**Comment by magic-akari** [comment]
关于第一点，还是不太清楚。
在 server/server.js 里有个函数 createWebAPIRequest 和 createRequest 。
剩下的是 express 的路由。

这好像就是利用 express 把这些请求转发出去。

伪造 refer 头的代码在 createWebAPIRequest 函数中完成。
并没有看出来 express 在这里是必要的。

把 createWebAPIRequest 和 createRequest 拿出来，
放到 app/server/index.js 中，是否能达到同样的目的，从而去掉了 express 的依赖？

**Comment by disoul** [comment]
你说的没错
上express一方面是为了路由考虑，一方面还有session cookies的考虑
毕竟裸写太麻烦啦  

---

而且我一开始设想是把这玩意能单独分离出来（就是希望我在网页上也能正常看
就做了一个代理层
